## Numpyの学習

In [1]:
import pandas as pd
import numpy as np

In [2]:
list = [1, 2, 3, 4]
print(list)

nd_array = np.asarray(list)
print(type(nd_array))
print(nd_array)

[1, 2, 3, 4]
<class 'numpy.ndarray'>
[1 2 3 4]


In [5]:
array = [[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
print(array)

nd_array = np.asarray(array)
print(type(nd_array))
print(nd_array)
print(nd_array[0])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
