## Numpyの学習

In [2]:
import pandas as pd
import numpy as np

In [3]:
list = [1, 2, 3, 4]
print(list)

nd_array = np.asarray(list)
print(type(nd_array))
print(nd_array)

[1, 2, 3, 4]
<class 'numpy.ndarray'>
[1 2 3 4]


In [4]:
array = [[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
print(array)

nd_array = np.asarray(array)
print(type(nd_array))
print(nd_array)
print(nd_array[0])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


dtypeを使って事前に型を指定することも可能

In [5]:
array = [[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
print(np.asarray(array, dtype=np.int64))
print(np.asarray(array, dtype=np.int64).tolist())
print(np.asarray(array, dtype=np.float64))
print(np.asarray(array, dtype=np.float64).tolist())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]


#### ndarrayの構造確認

In [6]:
print('3次元、2行、4列、int型')
nda = np.zeros((3, 2, 4), dtype=np.int64)
print(nda)
print('.' * 80)
print('次元:{}'.format(nda.ndim))
print('要素数:{}'.format(nda.size))
print('次元ごとの要素数:{}'.format(nda.shape))
print('バイト数:{}'.format(nda.nbytes))
print('dtype型:{}'.format(nda.dtype))

3次元、2行、4列、int型
[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
................................................................................
次元:3
要素数:24
次元ごとの要素数:(3, 2, 4)
バイト数:192
dtype型:int64


#### 行、列の取り出し

In [7]:
list = [[1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20],
        [21,22,23,24,25]]

nda = np.asarray(list)
print(nda)
print('.' * 80)
print('1行: {}'.format(nda[0,:]))
print('1列: {}'.format(nda[:,0]))
print('5行: {}'.format(nda[4,:]))
print('5列: {}'.format(nda[:,4]))
print('3行3列: {}'.format(nda[2,2]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
................................................................................
1行: [1 2 3 4 5]
1列: [ 1  6 11 16 21]
5行: [21 22 23 24 25]
5列: [ 5 10 15 20 25]
3行3列: 13


#### 数値演算

In [8]:
a = np.asarray([1, 2, 3, 4, 5])
b = np.asarray([6, 7, 8, 9, 10])
print('.' * 80)
print('add: {}'.format(np.add(a, b)))
print('subtract: {}'.format(np.subtract(a, b)))
print('multiply: {}'.format(np.multiply(a, b)))
print('divide: {}'.format(np.divide(a, b)))
print('mod: {}'.format(np.mod(b, a)))
print('power: {}'.format(np.power(a, b)))
print('sin: {}'.format(np.sin(b)))


................................................................................
add: [ 7  9 11 13 15]
subtract: [-5 -5 -5 -5 -5]
multiply: [ 6 14 24 36 50]
divide: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
mod: [0 1 2 1 0]
power: [      1     128    6561  262144 9765625]
sin: [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]


#### ファイル入出力

In [11]:
list = [[1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20],
        [21,22,23,24,25]]

nda = np.asarray(list)

np.save('nda.npy', nda)
nda_loaded = np.load('nda.npy')
print(nda_loaded)

np.savetxt('ndatext.npy', nda)
nda_loaded = np.loadtxt('ndatext.npy')
print(nda_loaded)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]
